### ISSUE TITLE
Logo design

### ISSUE THREAD

**Issue by aliwaris0572** [aliwaris0572/Snappy#1]
@maaudrana

**Comment by masudr4n4** [comment]
Do you have any requirements or idea then let me know.Or please tell more details about this app so that i can give more effect on logo to recognised about project😘😘😘

**Comment by aliwaris0572** [comment]
Its a library about animating toolbar. You can check the gifs [here](https://github.com/aliwaris0572/Snappy/blob/master/README.md). Gifs speak better than words ;)

**Comment by masudr4n4** [comment]
If you have any idea how well the logo is. Will it be the reload logo or the toolbox logo?

**Comment by aliwaris0572** [comment]
you can consider it as a loader library. Basically, it can be used when some long task is running in the background so that the user can be given something good to look at.

**Comment by masudr4n4** [comment]
if you need anything change please comment 

![snappy-01](https://user-images.githubusercontent.com/34313493/41680381-24ce6d98-74f3-11e8-9020-da08349fd14a.jpg)

**Comment by aliwaris0572** [comment]
You can make something with different gradients, just like the toolbar animates. This logo seems to be something like a doctor's app. :)

**Comment by masudr4n4** [comment]
![snappy1-01](https://user-images.githubusercontent.com/34313493/41812788-78373352-774b-11e8-934a-d231189d550d.jpg)
